### ISSUE TITLE
npm install error 不能 起服务

### ISSUE THREAD

**Issue by androidlsl** [jgsrty/netease-music-demo#3]
主分支 和vue2 都一样

**Comment by jgsrty** [comment]
具体报错信息能贴一下吗 我看看

**Comment by androidlsl** [comment]
![image](https://user-images.githubusercontent.com/15903494/115698888-b101b380-a397-11eb-8b39-fbf2562966a6.png)
vue2

主分支
![image](https://user-images.githubusercontent.com/15903494/115700554-5d906500-a399-11eb-8175-3eb6844808cc.png)

**Comment by jgsrty** [comment]
> 主分支 和vue2 都一样
![image](https://user-images.githubusercontent.com/25652828/115701019-e7d8c900-a399-11eb-8ebc-66ecac3f640d.png)
类似这种报错 你找到代码里面对应的位置 把引用路径的大小写手动转换下就行了

**Comment by androidlsl** [comment]
不单单是路径问题
刚开始第一个就是这个错误
![image](https://user-images.githubusercontent.com/15903494/115701759-b01e5100-a39a-11eb-9380-1c64cd6b4889.png)

**Comment by jgsrty** [comment]
你把 ‘@/api/Home’ 这个路径也改下大小写 你看对应的文件 应该是小写的

**Comment by jgsrty** [comment]
git默认配置是忽略了大小写的 类似这种报错手动改下就行 等我有空了把这个统一下
